export const GET_MOVIE_BY_ID_START = 'GET_MOVIE_BY_ID_START';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const GET_MOVIE_BY_ID_FAIL = 'GET_MOVIE_BY_ID_FAIL';

export const GET_TRAILER_BY_ID_START = 'GET_TRAILER_BY_ID_START';
export const GET_TRAILER_BY_ID_SUCCESS = 'GET_TRAILER_BY_ID_SUCCESS';
export const GET_TRAILER_BY_ID_FAIL = 'GET_TRAILER_BY_ID_FAIL';
