export const GET_MOVIES_POPULARES_START = 'GET_MOVIES_POPULARES_START';
export const GET_MOVIES_POPULARES_SUCCESS = 'GET_MOVIES_POPULARES_SUCCESS';
export const GET_MOVIES_POPULARES_FAIL = 'GET_MOVIES_POPULARES_FAIL';
export const GET_MOVIES_ESTRENOSIMPRESCINDIBLES_START =
  'GET_MOVIES_ESTRENOSIMPRESCINDIBLES_START';
export const GET_MOVIES_ESTRENOSIMPRESCINDIBLES_SUCCESS =
  'GET_MOVIES_ESTRENOSIMPRESCINDIBLES_SUCCESS';
export const GET_MOVIES_ESTRENOSIMPRESCINDIBLES_FAIL =
  'GET_MOVIES_ESTRENOSIMPRESCINDIBLES_FAIL';
export const GET_MOVIES_TODALAFAMILIA_START = 'GET_MOVIES_TODALAFAMILIA_START';
export const GET_MOVIES_TODALAFAMILIA_SUCCESS =
  'GET_MOVIES_TODALAFAMILIA_SUCCESS';
export const GET_MOVIES_TODALAFAMILIA_FAIL = 'GET_MOVIES_TODALAFAMILIA_FAIL';
export const GET_MOVIES_ESTRENOSESPANIOLES_START =
  'GET_MOVIES_ESTRENOSESPANIOLES_START';
export const GET_MOVIES_ESTRENOSESPANIOLES_SUCCESS =
  'GET_MOVIES_ESTRENOSESPANIOLES_SUCCESS';
export const GET_MOVIES_ESTRENOSESPANIOLES_FAIL =
  'GET_MOVIES_ESTRENOSESPANIOLES_FAIL';
export const GET_MOVIES_SITEPERDISTE_START = 'GET_MOVIES_SITEPERDISTE_START';
export const GET_MOVIES_SITEPERDISTE_SUCCESS =
  'GET_MOVIES_SITEPERDISTE_SUCCESS';
export const GET_MOVIES_SITEPERDISTE_FAIL = 'GET_MOVIES_SITEPERDISTE_FAIL';
export const GET_MOVIES_SI_TE_PERDISTE_START =
  'GET_MOVIES_SI_TE_PERDISTE_START';
export const GET_MOVIES_SI_TE_PERDISTE_SUCCESS =
  'GET_MOVIES_SI_TE_PERDISTE_SUCCESS';
export const GET_MOVIES_SI_TE_PERDISTE_FAIL = 'GET_MOVIES_SI_TE_PERDISTE_FAIL';
