export const GET_MOVIES_LATEST_START = 'GET_MOVIES_LATEST_START';
export const GET_MOVIES_LATEST_SUCCESS = 'GET_MOVIES_LATEST_SUCCESS';
export const GET_MOVIES_LATEST_FAIL = 'GET_MOVIES_LATEST_FAIL';
